# Generated by Django 5.0.3 on 2024-05-06 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSealsStampSafe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numbers_imprint_individual_seal', models.TextField()),
                ('number_safe', models.TextField()),
                ('registration_issue_date', models.DateField()),
                ('author_position_signature', models.TextField(null=True)),
                ('return_date', models.DateField(null=True)),
                ('security_signature', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author_admin_security', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_admin_security', to=settings.AUTH_USER_MODEL)),
                ('author_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_position_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'record_seals_stamp_safe',
            },
        ),
    ]
