# Generated by Django 5.0.6 on 2024-05-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_useragreement'),
        ('record_seals_stamp_safe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsealsstampsafe',
            name='author_position_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature', to='app.signinvate'),
        ),
        migrations.AlterField(
            model_name='recordsealsstampsafe',
            name='security_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_admin_security', to='app.signinvate'),
        ),
    ]
