# Generated by Django 5.0.3 on 2024-05-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_signinvate_sing'),
        ('record_seals_stamp_safe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordsealsstampsafe',
            name='author_admin_security',
        ),
        migrations.RemoveField(
            model_name='recordsealsstampsafe',
            name='author_position',
        ),
        migrations.AlterField(
            model_name='recordsealsstampsafe',
            name='author_position_signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='app.signinvate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordsealsstampsafe',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordsealsstampsafe',
            name='security_signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signature_admin_security', to='app.signinvate'),
            preserve_default=False,
        ),
    ]
