# Generated by Django 5.0.3 on 2024-05-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_signinvate_sing'),
        ('record_seals_stamp_safe', '0003_alter_recordsealsstampsafe_author_position_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsealsstampsafe',
            name='security_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_admin_security', to='app.signinvate'),
        ),
    ]
