# Generated by Django 5.0.3 on 2024-05-06 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRegistrationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_device_beckup_info', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_sign', models.DateTimeField(null=True)),
                ('user_sign', models.TextField(default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_registration_log',
            },
        ),
    ]
