# Generated by Django 5.0.6 on 2024-05-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_useragreement'),
        ('backup_registration_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupregistrationlog',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='backupregistrationlog',
            name='user_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_backup', to='app.signinvate'),
        ),
    ]
