# Generated by Django 5.0.3 on 2024-05-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_registration_log', '0003_alter_backupregistrationlog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupregistrationlog',
            name='date_sign',
        ),
    ]
