version: '3.8'
services:
  journal-app:
    container_name: journal_app
    restart: always
    build: .
    networks:
      - db_network
      - web_network
    environment:
      - DEBUG=1
    env_file: .env

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - journal-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 