# Generated by Django 5.0.6 on 2024-05-12 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRegistrationLogVPRP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_device_beckup_info', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_backup_vprp', to='app.signinvate')),
            ],
            options={
                'db_table': 'backup_registration_log_vprp',
            },
        ),
    ]
