# Generated by Django 5.0.6 on 2024-05-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_kzi_nki_kned_diia', '0003_alter_accounting_kzi_nki_kned_diia_accounting_kzi_nki_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_kzi_nki_kned_diia',
            name='inverter_numbers_peom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
