# Generated by Django 5.0.6 on 2024-05-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_kzi_nki_kned_diia_main_site', '0003_alter_accounting_kzi_nki_kned_diia_main_site_accounting_kzi_nki_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_kzi_nki_kned_diia_main_site',
            name='tool_kzi_type',
            field=models.SmallIntegerField(choices=[(1, 'Шлюз захисту "Бар`єр-301"'), (2, 'Мережевий IP-шифратор "Канал-401"'), (3, 'Мережний криптомодуль "Гряда-301" мікропристрій'), (4, 'Мережний криптомодуль "Гряда-301" ВП'), (5, '"Електронний ключ" Алмаз-1К'), (6, '"Електронний ключ" Кристал-1')]),
        ),
    ]
