# Generated by Django 5.0.6 on 2024-05-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_kzi_nki_kned_diia_software_tools', '0004_alter_accounting_kzi_nki_kned_diia_software_tools_tool_kzi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_kzi_nki_kned_diia_software_tools',
            name='inverter_numbers_peom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
