# Generated by Django 5.0.6 on 2024-05-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPRPTOITC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numbers_jornal', models.CharField(max_length=32)),
                ('denotation_vprp_basis', models.CharField(max_length=32)),
                ('denotation_vprp_date', models.DateField()),
                ('connection_information_vprp_basis', models.CharField(max_length=32)),
                ('connection_information_vprp_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, default=None, null=True)),
                ('connection_information_vprp_sysadmin_sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_information_vprp_admin_sign', to='app.signinvate')),
                ('denotation_vprp_sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denotation_vpr_sign', to='app.signinvate')),
                ('disconectation_vprp_seqadmin_sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disconectation_vprp_seqadmin_sign', to='app.signinvate')),
                ('disconectation_vprp_sysadmin_sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disconectation_vprp_sysadmin_sign', to='app.signinvate')),
            ],
            options={
                'db_table': 'vpr_to_itc',
            },
        ),
    ]
