# Generated by Django 5.0.6 on 2024-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpr_to_itc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vprptoitc',
            name='connection_information_vprp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
