# Generated by Django 5.0.6 on 2024-05-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_useragreement'),
        ('vpr_to_itc', '0002_alter_vprptoitc_connection_information_vprp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vprptoitc',
            name='connection_information_vprp_sysadmin_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_information_vprp_admin_sign', to='app.signinvate'),
        ),
        migrations.AlterField(
            model_name='vprptoitc',
            name='denotation_vprp_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denotation_vpr_sign', to='app.signinvate'),
        ),
        migrations.AlterField(
            model_name='vprptoitc',
            name='disconectation_vprp_seqadmin_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconectation_vprp_seqadmin_sign', to='app.signinvate'),
        ),
        migrations.AlterField(
            model_name='vprptoitc',
            name='disconectation_vprp_sysadmin_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconectation_vprp_sysadmin_sign', to='app.signinvate'),
        ),
    ]
