# Generated by Django 5.0.6 on 2024-05-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpr_to_itc', '0003_alter_vprptoitc_connection_information_vprp_sysadmin_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vprptoitc',
            name='connection_information_vprp_basis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
