# Generated by Django 5.0.6 on 2024-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('security_admin', 'Адміністратор безпеки'), ('system_admin', 'Системний адміністратор'), ('reg_cert_admin', 'Адміністратор реєстрації та сертифікації'), ('audit_admin', 'Адміністратор аудиту'), ('vzi', 'ВЗІ'), ('var', 'ВАР')], max_length=32),
        ),
    ]
