# Generated by Django 5.0.6 on 2024-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
