# Generated by Django 5.0.6 on 2024-05-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_useragreement'),
        ('key_data_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydatalog',
            name='admin_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_sign_key_data', to='app.signinvate'),
        ),
        migrations.AlterField(
            model_name='keydatalog',
            name='user_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sign_key_data', to='app.signinvate'),
        ),
    ]
