# Generated by Django 5.0.6 on 2024-05-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_data_log', '0002_alter_keydatalog_admin_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keydatalog',
            name='number_document',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
